export const DAYS_OF_WEEK = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

export const INGREDIENT_UNIT_LOOKUP: Record<string, string> = {
  g: "grams",
  gram: "grams",
  grams: "grams",
  kg: "kilograms",
  kilogram: "kilograms",
  kilograms: "kilograms",
  ml: "millilitres",
  millilitre: "millilitres",
  millilitres: "millilitres",
  l: "litres",
  litre: "litres",
  litres: "litres",
  tsp: "teaspoon",
  teaspoon: "teaspoon",
  tbsp: "tablespoon",
  tablespoon: "tablespoon",
  oz: "ounces",
  ounce: "ounces",
  ounces: "ounces",
  lb: "pounds",
  pound: "pounds",
  pounds: "pounds",
  cup: "cups",
  cups: "cups",
  piece: "pieces",
  pieces: "pieces",
  each: "pieces",
  // Add more as needed
};
